import { Context, Next } from "hono";
import { AuthVariables, authenticateRequest } from "./auth";
import { verifyUploadSignature } from "../utils/upload-signature";
import logger, { serializeError } from "../utils/logger";

/**
 * Allows POST /upload requests to authenticate either with a real API key /
 * session (as usual), or with a short-lived presigned signature generated by
 * POST /upload/sign. The presigned signature is scoped to a single `folder`
 * and expires after a server-defined window, so it's safe to hand to an
 * untrusted browser client.
 */
export async function presignedOrApiKeyAuth(c: Context<AuthVariables>, next: Next) {
  const authed = await authenticateRequest(c);

  if (authed) {
    await next();
    return;
  }

  const API_SECRET = process.env.API_SECRET;

  if (API_SECRET) {
    try {
      const formData = await c.req.formData();
      const signature = formData.get("signature");
      const expiresRaw = formData.get("expires");
      const folder = (formData.get("folder") as string | null) ?? "";

      if (typeof signature === "string" && typeof expiresRaw === "string") {
        const expires = Number(expiresRaw);

        if (verifyUploadSignature(signature, folder, expires, API_SECRET)) {
          if (Math.floor(Date.now() / 1000) > expires) {
            return c.json(
              { success: false, error: "Presigned upload URL has expired" },
              401
            );
          }

          c.set("user", null);
          c.set("apiKey", null);
          await next();
          return;
        }
      }
    } catch (error) {
      logger.error(
        { error: serializeError(error) },
        "Error verifying presigned upload signature"
      );
    }
  }

  return c.json(
    {
      error: "Authentication required",
      message:
        "Please provide a valid API key (Authorization: Bearer <key>), valid session cookie, or a presigned upload signature",
    },
    401
  );
}
